################################################################
# Program:
#	makefile
# Author:
#	Samuel Hibbard
# Summary:
#	Main makefile
################################################################

mac:
	make -f makefile.mac

ub:
	make -f makefile.ub

####################################
# Useful commands
####################################
clean:
	rm sim *.o simDebug