################################################################
# Program:
#	makefile
# Author:
#	Samuel Hibbard
# Summary:
#	This will be the main makefile.
################################################################

mac:
	make -f makefile.mac

ub:
	make -f makefile.ub

clean:
	rm *.o