###########################################################################
# Program:
#   makefile
# Author:
#   Samuel Hibbard
# Details
#   This will compile all the tests and create an execution file.
###########################################################################

test.out: driver.cpp node_test.h
	g++ -o test.out driver.cpp -lgtest